# Detailed outline {#outline}

```{r include=FALSE}
library(tidyverse)  # fussy, but might be useful later on
library(knitr)
library(kableExtra)
schedule <- tribble(
  ~item, ~date, ~title, ~notes, ~video, ~slides, ~link_name, ~link_url,
  "Leson 1", NA, "An Invitation to Data Visualization", "(#ch-invitation)", "(https://dal.brightspace.com/d2l/le/content/159870/viewContent/2139938/View)", "(slides/01-invitation.html)", NA, NA,
  "Synchronous meeting", "2021-01-07 08:35", "[Agenda](#sync-1)", NA, NA, NA, "Collaborate (Brightspace)", "(https://dal.brightspace.com/d2l/le/content/159870/viewContent/2083793/View)",
)
sh <- function(i, shedule = schedule) {
  schedule %>% slice(i) %>%
    mutate(notes = case_when(!is.na(notes) ~ paste0("[Notes]", notes), TRUE ~ notes),
           video = case_when(!is.na(video) ~ paste0("[Video]", video), TRUE ~ video),
           slides = case_when(!is.na(slides) ~ paste0("[Slides]", slides), TRUE ~ slides),
           link = case_when(!is.na(link_url) ~ paste0("[", link_name, "]", link_url), TRUE ~ as.character(NA))) %>%
    kable() %>% kableExtra::kable_styling()
}
```

Synchronous sessions will be held on Thursday starting at 8:35 and ending at 9:55 or earlier. You can find the link to these sessions on [Brightspace](https://dal.brightspace.com/d2l/le/content/159870/Home?itemIdentifier=D2L.LE.Content.ContentObject.ModuleCO-2083791). There is an [agenda](#sync) for each session.  Most sessions will be recorded and posted on Brightspace. The other synchronous time in the timetable (Tuesday starting at 8:35) will be used for drop-in office hours. 

## Course calendar

**This is a tentative schedule which will be revised throughout the term.**

Each lesson has written notes, a recorded video (with slides), and links to textbook readings. There is some duplication across these materials. Some students will prefer to begin with the video, others will prefer to begin with the written notes and slides. I suggest you learn which you prefer by experimentation. The tasks are designed to be sure you know the most important parts of each lesson.

### Week 0: Before the course begins

An introduction to the course is provided by a welcome presentation called Course Mechanics: [video](https://dal.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=9eabe994-44ad-42b8-9db3-aca00024fe2b) and [slides](slides/00-course-mechanics.html). After you watch this video, review the [course welcome](#welcome) and [syllabus](#syllabus). Then move on to Week 1.

### Week 1: Jan 6-8

These lessons introduce the content of the course and the tools we will use. 

Work on these elements in the following suggested order:

- Lesson 1: An Invitation to Data Visualization. [Notes](#ch-invitation), [Video](https://dal.brightspace.com/d2l/le/content/159870/viewContent/2139938/View), [Slides](slides/01-invitation.html).
- Synchronous meeting Thursday 7 January, 8:35 Atlantic on [Collaborate (Brightspace)](https://dal.brightspace.com/d2l/le/content/159870/viewContent/2083793/View). [Agenda](#sync).
- Lesson 2: The tools we will use and why: R, Rstudio, ggplot, tidyverse, markdown, git, github. [Notes](#ch-tools), Video, [Slides](slides/02-computer-tools.html)
- Task 1. [Instructions](#task-1). Submit on Brightspace.

Task 1 is due Monday 11 January at 9:00 am Atlantic time.

### Week 2: Jan 11-15

The three lessons this week show you how to get your computer set up for the course, discuss how we perceive visualizations, and how to make your own simple scatter plot.

- Lesson 3: Installing R, Rstudio, packages, creating github account. [Notes](#setup), [Video](https://dal.brightspace.com/d2l/le/content/159870/Home?itemIdentifier=D2L.LE.Content.ContentObject.ModuleCO-2083726).
- Task 2. [Instructions](#task-2). Submit on Brightspace.
- Office hours. Tuesday 12 January, 8:35 Atlantic on Collaborate. If you are having trouble with Task 2, come at this time for help.
- Lesson 4: Look at data. [Notes](#look-data), Video, [Slides](slides/04-look-at-data.html)
- Task 3. [Instructions](#task-3). Submit on Brightspace.
- Lesson 5: Making your first plot. [Notes](#first-plot), Video, [Slides](slides/05-making-your-first-plot.html)
- Synchronous meeting Thursday 14 January, 8:35 Atlantic on Collaborate. Live coding material: [R markdown](static/live-coding-01.rmd), [html](static/live-coding-01.html).  [Agenda](#sync).

Tasks 2 and 3 are due Monday 18 January at 9:00 am Atlantic time. 


### Week 3: Jan 18-22

These lessons show you how and why we will use git in this course, describe the design of the grammar of graphics which we will use to make visualizations, and show you more examples of making plots.

- Lesson 6: Version control concepts and working with git. [Notes](#vcs), Video, [Slides](slides/06-version-control.html).
- Task 4. [Instructions](#task-4). Nothing to submit. This is preparation for Assignment 1. Everyone who *submits* Assignment 1 on time will get 10/10 for this task.
- Office hours. Tuesday 19 January, 8:35 Atlantic on Collaborate. If you are having trouble with Task 4, come to these office hours with your questions.
- Lesson 7 Introduction to the Grammar of Graphics. [Notes](#grammar), Video, [Slides](slides/07-grammar.html)
- Lesson 8 Make a plot. [Notes](#ggplot), Video, [Slides](slides/08-ggplot.html)

- Assignment 1. [Instructions](#assignment-1). Submit on github.
- Synchronous meeting Thursday 21 January, 8:35 Atlantic on Collaborate. Live coding material: [R markdown](static/live-coding-02.rmd), [html](static/live-coding-02.html).  [Agenda](#sync).

Connect your github account to our course on github and get access to the repository for Task 4 and Assignment 1 by clicking [here](https://classroom.github.com/a/FWE3dcDr). You will be asked to join the github organization "Dalhousie-AndrewIrwin-Teaching" and then select your name from a list of students. If your name does not appear in the list, please contact me so I can add your name to the list of students.

Assignment 1 is due Wednesday 27 January at 6:00 pm Atlantic time.

### Week 4: Jan 25-29

- Lesson 10 Show the right numbers. [Healy Chapter 4](https://socviz.co/groupfacettx.html#groupfacettx)
- Office hours. Tuesday 26 January, 8:35 Atlantic on Collaborate.
- Task 5. Check out from and sumbit on github.
- Lesson 11 Summarizing data with dplyr (group_by, filter, mutate, summarize)
- Lesson 12 Display and graph tables, add labels, make notes. [Healy Chapter 5](https://socviz.co/workgeoms.html#workgeoms)
- Synchronous meeting Thursday 28 January, 8:35 Atlantic on Collaborate. Live coding material: [R markdown](static/live-coding-03.rmd), [html](static/live-coding-03.html).  [Agenda](#sync).
- Task 6. Check out from and submit on github.

Tasks 5 and 6 are due Monday 1 February at 9:00 am Atlantic time. Complete both tasks using the same repository. 

Assignment 2 is due Wednesday 3 February at 6:00 pm Atlantic time.

Click the following links to get two repostories: [tasks-5+6](no link yet) and [assignment-2](no link yet).


### Week 5: Feb 1-5

- [Lesson 13](#reading-data) Reading data (csv, tsv, xlsx); import menu item; r commands
- Office hours. Tuesday 2 February, 8:35 Atlantic on Collaborate.
- [Lesson 14](#pivot) Reshaping data
- [Lesson 15](#facets) Plotting small multiples (facets)
- Lesson 16 Scales: shape, color, lines, and more. [Notes](#ggplot2), Video, [Slides](slides/09-ggplot-custom.html)
- Task 7 and 8. Check out from and submit on github.

Tasks 7 and 8 are due Monday 8 February at 9:00 am Atlantic time. Complete both tasks using the same [repository](no link yet). 

### Week 6: Feb 8-12

- Lesson 16 Work with models. [Healy Chapter 6](https://socviz.co/modeling.html#modeling)
- Lesson 17 Linear models (lines, polynomials, robust, quantile); equationomatic 
- Lesson 18 LOESS, GAM

Tasks 11 and 12 are due Monday 22 February at 9:00 am Atlantic time. Complete both tasks using the same repository. 
Assignment 3 is due Friday 12 February at 6:00 pm Atlantic time. (Change in due date to keep time free during the break for other projects.)

Follow these links to get two repostories: [tasks-11+12](no link yet) and [assignment-3](no link yet).

You will receive an invitation to a term project repository on Friday 12 February.

### Week 7: Feb 22-26

- Lesson 19 PCA
- Lesson 20 MDS 
- Lesson 21 K-means

Tasks 13 and 14 are due Monday 1 March  at 9:00 am Atlantic time. Complete both tasks using the same repository. 

### Week 8: Mar 1-5

- Reproducible reports and R markdown
- Slide presentations using R markdown

Tasks 15 and 16 are due Monday 8 March  at 9:00 am Atlantic time. Complete both tasks using the same repository. 

Assignment 4 is due Wednesday 10 March at 6:00 pm Atlantic time.

### Week 9: Mar 8-12

- Lesson 22 Tidy data; Making data tidy (datapasta)
- Lesson 23 Data validation (pointblank)
- Lesson 24 Finding, describing data with metadata (codebook)

Tasks 17 and 18 are due Monday 15 March  at 9:00 am Atlantic time. Complete both tasks using the same repository. 

- Project proposal due Friday 12 March at 6:00 pm Atlantic.

### Week 10: Mar 15-19

- Lesson 25 Draw maps. [Healy Chapter 7](https://socviz.co/maps.html#maps)
- Lesson 26 Making maps and chloropleths. Heatmaps.
- Lesson 27 Refine your plots. [Healy Chapter 8](https://socviz.co/refineplots.html#refineplots). Ordering factors.

- Synchronous session. Thursday 18 March. Review of selected work from Assigment 4 (sharing ideas and techniques)

Tasks 19 and 20 are due Monday 22 March  at 9:00 am Atlantic time. Complete both tasks using the same repository. 

Assignment 5 is due Wednesday 24 March at 6:00 pm Atlantic time.

### Week 11: Mar 22-26

- Lesson 28 Themes
- Lesson 29 Annotations
- Lesson 30 Graphics output (PDF, png, sizes, colors, themes; ragg) repurposing graphics for different media and purposes

- Synchronous session. Thursday 18 March. Review of selected work from Assigment 5 (sharing ideas and techniques) and problem solving for visualizations you are trying to create for presentation in a week. Send me your questions or challenges in advance.

Tasks 21 and 22 are due Monday 29 March  at 9:00 am Atlantic time. Complete both tasks using the same repository. 

### Week 12: Mar 29-April 1

- graphs for categorical data
- graphs for quantitative data
- Working with dates

- Synchronous session. Thu 1 April, 8:35 Atlantic. Oral presentations day 1. [Agenda](#sync).

No more tasks.

Assignment 6 due Wednesday 7 April at 6:00 pm. Peer assessment of two randomly selected oral presentations. Submit on github.

### Week 13: Apr 5-8

- Synchronous session. Tue 6 April, 8:35 Atlantic. Oral presentations day 2. [Agenda](#sync).

Project report due Friday 9 April, 6:00 pm Atlantic. Submit on github.

## Bonus Material

- [Data sources](#data)
- [Staying organized](#organization)
- Getting help: solving problems and asking questions
- [A bit more about R](#r-details). 
- Using R markdown for reproducibility and report writing
- Collaborating with git
- A tour of plot types
- Learning computing tools on your own (project overview)
- What is the tidyverse? Contrast with other conventions
- How do I know I've done it right?
- Text data and regular expressions introduction
- Examples of building up figures step by step
- Working with dates and times

