# Synchronous meeting agendas {#sync}

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We have 13 synchronous sessions. The last two will be used for oral presentations.

## Thu 7 Jan 8:35 {#sync-1}

Before the meeting: 

* Review Week 0 material (in the [detailed outline](#outline))
* Watch the video for Lesson 1

Meeting agenda:

* Course goals
* How the course works
* Purpose of each component (recorded videos, notes, slides, textbook readings, evaluation activities)
* Questions and discussion
* Demonstration of basics of Rstudio

## Tue 12 Jan 8:35

This is a drop-in office hour. Come with questions about the course. In particular, if you are having difficulty settung up R, Rstudio, git, bring those questions.

## Thu 14 Jan 8:35 {#sync-2}

Before the meeeting:

* Work up to Lesson 4 or 5

Meeting agenda:

* Introduce how R markdown documents work and why we use them
* Live coding examples from Lesson 5 and Lesson 6
* Questions and discussion

Links to the [HTML](https://htmlpreview.github.io/?https://github.com/AndrewIrwin/data-visualization/blob/master/live-coding/live-coding-02.html) and [Rmd](https://raw.githubusercontent.com/AndrewIrwin/data-visualization/master/live-coding/live-coding-02.rmd) versions of our live coding exercises for this meeting. To download the file you should right (or control) click the Rmd link to save the file to your computer. Read through the HTML version. Download the Rmd version to your computer and open it up in Rstudio. After class you can access the [knitted HTML](https://htmlpreview.github.io/?https://github.com/AndrewIrwin/data-visualization/blob/master/live-coding/live-coding-02-after-class.html) and [Rmd](https://raw.githubusercontent.com/AndrewIrwin/data-visualization/master/live-coding/live-coding-02-after-class.rmd) versions we created.



## Tue 19 Jan 8:35

This is a drop-in office hour. Come with questions about the course. In particular, you may want to bring questions about Task 4 or Assignment 1.

## Thu 21 Jan 8:35 {#sync-3}

Before the meeeting:

* Work up to Lesson 8

Meeting agenda:

* Live coding examples of using ggplot

## Tue 26 Jan 8:35

This is a drop-in office hour. Come with questions about the course.

## Thu 28 Jan 8:35 {#sync-4}

Before the meeeting:

* Lesson 11

Meeting agenda:

* Live coding examples using `dplyr` tools





## Thu 1 April 8:35 {#sync-12}

Oral presentations day 1. Each presentation will be a maximum of 5 minutes, so there will be time for about 12 presentations.

A sign-up sheet will be posted on Brightspace once the proposals have been submitted.

Presentations may be made live or can be pre-recorded.

## Tue 6 April 8:35 {#sync-13}

This is not an office hour day, but instead is a required synchronous session.

Oral presentations day 2. Each presentation will be a maximum of 5 minutes, so there will be time for about 12 presentations.

A sign-up sheet will be posted on Brightspace once the proposals have been submitted.

Presentations may be made live or can be pre-recorded.

