# Evaluation {#evaluation}

All the work students will complete for evaluation and credit in the course is described below.

## Tasks

Tasks for each lesson are described here. Each task is designed to demonstrate a particular skill or idea from the lesson or prepare for the next lesson.

Tasks will usually be evaluated on a 0-10 scale on the following rubric:

* 0-5: Work missing or mostly incomplete.
* 6-7: Mostly complete or complete with major deficiencies.
* 8: Complete and meets expectations.
* 9-10: Complete and excels in some respect: organization, clarity, creativity. 

### Task 1 (Lesson 1) {#task-1}

Find two data visualizations that you find informative, compelling, or in need of improvement.

Create a document that shows each visualization (the figure, or a snapshot of a dynamic visualization), provides the source (e.g., url and publication details if applicable). In a few sentences describe 

1. the data behind the visualization, 
2. main message conveyed by the visualization,
3. one or two features of the visualization that make it effective or suggestions for improvement. 

The goal of this project isn't to be right or wrong, but rather to start the process of looking at data visualizations through the perspective of creator, designer, and critic. It's okay if you find visualizations from secondary sources and not the creator or original publisher. Include the reference to the source you used to find the visualiztions.

Submit your work as a single PDF on Brightspace.

### Bonus task (Lesson 2)

Read [Healy, Sections 2.1-2.4](https://socviz.co/gettingstarted.html#gettingstarted). There is nothing to submit for this task.

### Task 2 (Lesson 3) {#task-2}

See the instructions in the [syllabus](#syllabus_software) or in [Lesson 3 notes](#setup)

1. Install R, Rstudio, and the packages identified in Healy's [Preface](https://socviz.co/index.html#install).
2. Install git.
3. Create a github account. 
2. Login to [rstudio.cloud](https://rstudio.cloud/project/1998812). This is a complete R, Rstudio, and git setup "in the cloud" that can be used if you have trouble using R on your own computer.
5. Ask for help with any of these tasks if you need it. 

Answer the quiz on Brightspace which will ask if you were successful with each task or if you need help. Provide your github name in one of the quiz questions.

### Task 3 (Lesson 4) {#task-3}

1. Some people feel very strongly about the placement of 0 on the vertical scale of plots. Look again at the carbon dioxide plots in [Lesson 1](#ch_invitation). The vertical scale does not start at 0. Use the ideas in [Healy Chapter 1.6](https://socviz.co/lookatdata.html#problems-of-honesty-and-good-judgment) to describe how you would interpret vertical position on the carbon dioxide plots and how you could interpret this position if 0 was included on the vertical scale.

2. Hans Rosling's visualizations (as shown in [Lesson 1](#ch_invitation)) use many channels for conveying data: x and y position, color, size, an annotation for year in the plot background. The interactive versions use an animation for change over time, and mouse-over pop-ups to identify the country for each dot. These are very complex visualizations! 

a. For the plot linked above, what variables are shown for each of x and y position, color, and symbol size?
b. According to [Healy Chapter 1](https://socviz.co/lookatdata.html#channels-for-representing-data) which of these 4 features is most difficult to make quantitative comparisons with? Why? Do you agree? 
c. In your judgment, is this visualization effective or too complex. Watch the [TED talk](https://www.ted.com/talks/hans_rosling_the_best_stats_you_ve_ever_seen) or experiment with the [interactive version](https://bit.ly/3oAb0Uq) before answering the question.

Write answers for these two questions in a word processor (we'll start using R markdown soon) and submit as a single PDF on Brightspace. Assesment: 10 points total, 5 points per question.

### Task 4 (Lesson 6) {#task-4}

Use Rstudio to create a new project from the github repository for Assignment 1. This is a new task, but it's going to be a recurring task throughout the course. Here are step-by-step instructions. If you have trouble with this task, ask for help. It's very important.

* Look for an invitation in your email sent earlier this week.
* Copy the link.
* Use Rstudio, menu File > New Project > From repository... > Git. Insert the link to the repository and tell R where to put the repository on your computer (or in your Rstudio.cloud workspace.)
* If you use rstudio.cloud, start at the [projects](https://rstudio.cloud/projects) page and choose New Project from git repository (pop-up menu). rstudio.cloud must be linked to your github account to access private repositories. You'll get instructions on how to do this when you try to create a new project from a github repository. 

### Task 5 (Lesson 5) {#task-5}

Make the plot from Healy Section 2.6. Look at the other variables in the gapminder dataset and make some other plots of your choosing. Put your plots in an Rmd. Knit the R markdown file. Nothing to submit. Ask for help if you have problems.

### Task 6 (Lesson X) {#task-6}

Using scales effectively. Improving figures.
Diverging continuous colour
Colour blind tester
Hiding guides. Unifying guides.

### Task 7 (Lesson X) {#task-7}
dplyr summarize

### Task 8 (Lesson X) {#task-8}
tables

### Task 9 (Lesson X) {#task-9}
Reading data

### Task 10 (Lesson X) {#task-10}
Facets

### Task 11 (Lesson X) {#task-11}
Work with models

### Task 12 (Lesson X) {#task-12}
Add smooths to plots

### Task 13 (Lesson X) {#task-13}
PCA
### Task 14 (Lesson X) {#task-14}
MDS, Kmeans

### Task 15 (Lesson X) {#task-15}
### Task 16 (Lesson X) {#task-16}
### Task 17 (Lesson X) {#task-17}
### Task 18 (Lesson X) {#task-18}
### Task 19 (Lesson X) {#task-19}

### Task 20 (Lesson X) {#task-20}
### Task 21 (Lesson X) {#task-21}
### Task 22 (Lesson X) {#task-22}


## Assignments

Assignments are opportunities to apply and combine the skills from several lessons. They are both structured, in that you are asked to use specific skills to accomplish a task, and creative in that you have some flexibility in the product you produce. You will be assessed on your use of technical skills and your judgement in making well-designed and effective visualizations, following the principles explored in the course.

Assignments should be submitted to the relevant github repository, generally as an R markdown document.


### Assignment 1 {#assignment-1}

Make a simple markdown document with a figure and commit to a github repository. Ensures you know a foundation of of using git, github, R markdown, and ggplot to build new knowledge and skills on top.

### Assignment 2 {#assignment-2}

learn, describe, and use a ggplot extension. 
- ggridges, ggupset, ggrepel, cowplot, patchwork, viridislite
- violin, uncertainty displays (half eye, etc)


### Assignment 3 {#assignment-3}

learn, describe, and use a table layout package.
- DT, gt, flextable, kable/kableExtra

### Assignment 4 {#assignment-4}

[Tidy Tuesday]() is a weekly activity to support people learning to use R for data analysis and visualization. Each week a new dataset is posted and interested participants post their visualizations. Some are complex pieces of work by people with lots of experience, but many are the work of beginners just learning to make good visualizations. I encourage you to explore the datasets and example visualizations others have made as a source of ideas and inspiration.

For the next two assignments, I'll select a few datasets and ask you to work with one of those for your assignment.

For this assignment you will make scatter plots with smooths (linear, loess, or gam) and dimensionality reduction (PCA or MDS). The goal is to gain some insight into the data and present some aspect of the data in a visually appealing way. You may be able to use the data as its presented, or you may need to transform it in some way first (for example using the dplyr tools). You should feel free to show a subset of the data if you think that makes a better visualization to highlight a particular feature of the data.

Present your work as a short R markdown report. You should describe the dataset, explain any analysis or transformations you did, present at least 2 visualizations, and describe the main messages conveyed by your visualization. Full instructions are in the repostory.

### Assignment 5 {#assignment-5}

This is the second Tidy Tuesday assignment. You should create a map and some other analysis such as a data table or other visualization already discussed in class.

Organize your work as a slide presentation with presenter notes. An example and instructions are in the repository.

### Assignment 6 {#assignment-6}

This is a peer evaluation assignment. You should provide, in separate documents as described in the repository,

* confidental feedback on your team mates work for the term project
* a peer evaluation of two oral presentations from other teams, which will be shared with the presenters.

You should provide thoughtful and constructive feedback on the work of your classmates. Everyone's work has good aspects and areas where there could be improvement; you should aim to provide useful feedback in both areas.

Your assignment for the peer evaluation is in the project planning repository we all share. Pull an updated version from github after XXX to see your assigment. Remember to do this before the first day of presentations so you know which presentation to evaluate!

A rubric and guide for your evaluations is in the repository for this assignment.

## Term project

Your final project is an analysis on a dataset of your own choosing. You can choose the data based on your interests, based on work in other courses, or independent research projects. You should demonstrate many of the techniques from the course, applying them as appropriate to develop and communicate insight into the data.

You should create compelling visualizations of your data. Pay attention to your presentation: neatness, coherency, and clarity will count. All analyses must be done in RStudio using R.

### Deliverables

* Proposal - due Fiday 12 March at 6:00 pm
* Presentation - due Thursday 1 April or Tuesday 6 April during synchronous meeting.
* Report - due Friday 9 April at 6:00 pm

Work in groups of 2. You can produce team products, or one product per team member, whichever you prefer. You have two roles in the project. First you will contribute your original creative work for the project. Second, you will act as a collaborator, providing your teammate with feedback, suggestions, debugging help, proofreading and other assistance as requested.

Use a single github repository for the proposal, presentation, and final report. If you work in pairs, producing joint work, use the repository for one team member and add the other member to the repository. See the notes on [collaboration with github](#collaboration) for guidance.

### Proposal

Your main task for the proposal is to find a dataset to analyze for your project and describe at least one question you can address with data visualizations.

It is important that you choose a readily accessible dataset that is large enough so multiple relationships can be explored, but no so complex that you get lost. I suggest your dataset should have at least 50 observations and about 10 variables. The variables should include categorical variables, discrete numerical variables, and continuous numerical variables. If you plan to use a dataset that comes in a format that we haven’t encountered in class, make sure that you are able to load it into R as this can be tricky depending on the source. If you are having trouble ask for help before it is too late.

Do not reuse datasets from any part of the course.

Here is list of data repositories containing many interesting datasets. Feel free to use data from other sources if you prefer.

* [TidyTuesday](https://github.com/rfordatascience/tidytuesday)
* [Kaggle](https://www.kaggle.com/datasets) datasets
* [OpenIntro](https://www.openintro.org/book/statdata/index.php) datasets
* [Awesome public](https://github.com/awesomedata/awesome-public-datasets) datasets
* [Bikeshare](https://www.bikeshare.com/data/) data portal
* [Harvard Dataverse](https://dataverse.harvard.edu/)
* [Statistics Canada](https://www150.statcan.gc.ca/n1/en/type/data)
* Open government data: [Canada](https://open.canada.ca/en/open-data), [NS](https://data.novascotia.ca/), and many other sources
* Other sources listed in the [Data sources]() section of these notes or that you find on your own.

Describe a dataset and question you can address with the data for your report. How you plan to use 5 things (overview plot, dplyr/table summary, small multiples, knn/PCA, map)


Your proposal should include an Rmd document called proposal.rmd with the following sections and the proposed dataset.

* Introduction: The introduction should introduce your general research question and your data (where it came from, how it was collected, what are the cases, what are the variables, etc.).
* Data: Place your data in the /data folder, and add dimensions and codebook to the README in that folder. Include the output of `dplyr::glimpse()` or `skimr::skim()` on your data frame.
* Visualization and analysis plan:
  * The outcome (response, Y) and predictor (explanatory, X) variables you will use to answer your question.
  * Ideas for at least two possible visualizations for exploratory data analysis, including some summary statistics and visualizations, along with some explanation on how they help you learn more about your data.
  * An idea of how at least one statistical methods described in the course (smoothing, PCA, k-means) could be useful in analyzing your data


*Assessment*. Your proposal will be assessed for the following elements: a dataset is identifed and described (size of dataset, variables, source), a question to be investigated is clearly described, a visualization plan is presented. Scoring will be similar to exercises:

* 4 points (1 each) for the following 4 elements: description of data, size of data, source of data, question, 
* 2 points for a visualization plan
* 2 points for presentation quality, 
* 2 points for creativity / thoughtfulness / imagination

Total 10.

### Oral presentation

The oral presentation should be about 5 minutes long. The goal is to present the highlights of your project and allow for feedback which can be incorporated as you revise your written report.

You should have a small number of slides to accompany your presentation. I suggest a format such as the following:

* A title with your name
* A description of the data you are analyzing
* At least one question you can investigate with your data visualization
* At least two data visualizations
* A conclusion

A template for a presentation (presentation.rpres) is in the project repository.

Don't show your R code; the focus should be on your results and visualzations not your computing. Set `echo = FALSE` to hide R code (this is already done in the template).

Your presentation should not just be an account of everything you tried ("then we did this, then we did this, etc."), instead it should convey what choices you made, and why, and what you found.

Presentation schedule: Presentations will take place during the last workshop of the semester. You can choose to do your presentation live or pre-record it. During your workshop you will watch presentations from other teams in your workshop and provide feedback in the form of peer evaluations. The presentation line-up will be generated randomly.
 
### Written report

Required elements:

* README.rmd
* Data Dictionary
* Written report (report.rmd) presenting your visualizations and insights about your data

This write-up, which you can also think of as an summary of your project, should provide information on the dataset you’re using, your research question(s), your methodology, and your findings.

Repo organization
The following folders and files in your project repository:

presentation.Rmd + presentation.html: Your presentation slides
README.md: Your write-up
/data/*: Your dataset in csv or RDS format, in the /data folder.
/proposal: Your proposal from earlier in the semester

Style and format does count for this assignment, so please take the time to make sure everything looks good and your data and code are properly formated.

If you work in the same repository as your teammate, so merge conflicts will happen, issues will arise, and that’s fine! Commit and push often, and ask questions when stuck.

Review the marking guidelines below and ask questions if any of the expectations are unclear.

Code: In your presentation your code should be hidden (echo = FALSE) so that your document is neat and easy to read. However your document should include all your code such that if I re-knit your R Markdown file I should be able to obtain the results you presented. Exception: If you want to highlight something specific about a piece of code, you’re welcomed to show that portion.

Marking
Write-up	15 pts
Reproducibility and organization	10 pts
Team peer evaluation	10 pts
Classmates’ evaluation	5 pts

Criteria
Content - What is the quality of research and/or policy question and relevancy of data to those questions?
Correctness - Are statistical procedures carried out and explained correctly?
Writing and Presentation - What is the quality of the statistical presentation, writing, and explanations?
Creativity and Critical Thought - Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?




