---
title: "Evaluation in preparation material"
author: "Andrew Irwin"
date: "10/12/2020"
output: html_document
---

Material in preparation as tasks, assignments.

## Tasks

### Lesson X

Demonstrate use of group_by, filter, summarize.

R basics: c, str, class, typeof

Demonstrate facetted plots in a few ways.

Figure formatting. Axis labels. Legends. Colour scales. 

Work with dates using lubridate. Parsing, manipulating, plotting.

Learn to use a function from its help page. Learn about a dataset from its help page. Report in a Rmd document.

Learn somethign about dplyr from r4ds book. Demonstrate by solving an exercise.

Learn somethign from ggplot2 tidyverse website. Demonstrate. Give a menu of 2-3 tasks.

Demonstrate pivot longer and pivot wider.

Fix mistakes in code provided. (about 5 kinds of mistakes / error messages.)

Do a tidy tuesday. as Rmd

Do a tidy tuesday as slideshow. Make a Rmd slideshow to demonstrate creation of a figure and revision / elaboration. 5 slides.

Make 3 versions of same figure: Rmd version (webpage), pdf for printed page (b&w), slideshow (png, big fonts, simplify, extra colour)


Format a nice table using gt, kableExtra, etc

Demo one of the following packages: Upset, patchwork, ggrepel

demo one of the following: naniar, waldo, skimr

Draw a simple map. (points on a map)

Draw a more elaborate map. (colour scales, filled regions)

Sample knn calculation.

Sample PCA.
