# Assignments

### Overview

Assignments are opportunities to apply and combine the skills from several lessons. They are both structured, in that you are asked to use specific skills to accomplish a task, and creative in that you have some flexibility in the product you produce. You will be assessed on your use of technical skills and your judgement in making well-designed and effective visualizations, following the principles explored in the course.

Assignments should be submitted to the relevant github repository, generally as an R markdown document.

Assesment rubric:
* 0 none of the objectives met; document has errors that prevent knitting
* 1 some objectives met
* 2 some objectives met
* 3 no substantive errors
* 4 excellent work, clearly presented and thoughtfully designed



### Assignment 1

learn, describe, and use a ggplot extension. 5% (Week 7, after break)
- ggrepel, cowplot, patchwork, viridislite

### Assignment 
learn, describe, and use a table layout package. 5%  (Week 9)
- DT, gt, flextable, kable/kableExtra

(Do one as a 5 minute video with script and slides. Do the other as a rmd tutorial.)


### Assignment 

Mini-project: Tidy Tuesday 1. 5% (Week 10)

### Assignment

Mini-project: Tidy Tuesday 2. 5% (Week 11)


