
# Extra resources

## Courses

* [Introduction to Data Science](https://www.introds.org/) at University of Edinburg by Mine Çetinkaya-Rundel
* Web page for Kieran Healy's [Data visualization](http://socviz880.co/) course
* [Stat 545](https://stat545.com/)
* https://psyteachr.github.io/msc-data-skills/
* [Data Science in a Box](https://datasciencebox.org/)

## Books

* [Grammar of Graphics ggplot2 book](https://ggplot2-book.org/)
* [R Graphics Cookbook](https://r-graphics.org/)
* [R for Data Science Exercise solutions](https://jrnold.github.io/r4ds-exercise-solutions/)

* [Bookdown](https://bookdown.org/yihui/bookdown/) manual for writing longer documents with R Markdown

## Cheatsheets

Hosted at [Rstudio](https://rstudio.com/resources/cheatsheets/)

* [RStudio](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf)
* [R Markdown](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)
* [ggplot2](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf)
* [dplyr](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)


- [R markdown lessons](https://rmarkdown.rstudio.com/lesson-1.html)
- [Using git with R](https://happygitwithr.com/) (more than the basics) 
- [Data Science in a Box](https://datasciencebox.org/) by Mine Çetinkaya-Rundel

## General resources (not just R)
- https://datavizcatalogue.com/index.html


## Websites pointing to other websites:

Learn R for free: learnR4free.com


## Videos

Hour-long video overview of Rstudio features: https://www.youtube.com/watch?v=PXiY8muVUec


## Other

* A story about [starting to work as a data scientist](https://www.geekwire.com/2020/jacqueline-nolis/) and writing a [book about becoming a data scientist](https://www.manning.com/books/build-a-career-in-data-science).


